= Rationale
:URY: http://ury.org.uk

_BAPS3_ is an architecture for a radio playout suite, designed to replace the
playout suite, _BAPS2_, in use at {URY}[University Radio York] as of 2015.  As
such, it is primarily designed to build on the successes, and avoid the
failures, of that system.

The primary goals for BAPS3 are:

. To replace BAPS2 in use at University Radio York;
. To be easily modifiable, replaceable, and extensible;
. To take advantage of modern software, hardware and development technology;
. To be cross-platform (specifically focusing on Windows, Linux and FreeBSD);
. To be as reliable as, or more reliable than, BAPS2.

In addition to this, we hope that BAPS3 will:

. Be useful to other small (voluntary, community and student) radio stations;
. Be adaptable to the changing world of student radio;
. Allow a greater amount of flexibility within University Radio York than is
  currently available with BAPS2.

== The BAPS2 API

We consciously chose not to use the existing BAPS2 API, for the
following reasons:

* The BAPS2 API is based on a binary protocol that is difficult to
  debug, and provides a lack of transparency that outweighs the
  performance advantages of using the binary protocol;
* The HTTP-based external API allows Web-based implementations of
  the client service, amongst other flexibility benefits;
* The change from BAPS2 to BAPS3 allowed us to correct some oddities
  and counter-intuitive design decisions in the BAPS2 API.
