[site]
  title = "Bifrost Specification"
  # the 404 page and sitemap files only get generated when the url property is set
  url = "https://universityradioyork.github.io/baps3-spec"
  start_page = "bifrost::index.adoc"

[[content.sources]]
  url = "."
  start_path = "bifrost"
  branches = "master"

[ui.bundle]
  # source at github.com/MattWindsor91/ury-antora-ui
  # eventually it might be good to host this somewhere
  url = "./ui-bundle.zip"

