= Glossary

== BAPS3
The playout system specified in this document.

== API user
A user of a BAPS3 API; either a client or a server.

== client
A program or user that consumes services.

== external API
The API used for communication between BAPS3 clients and the server stack
providing BAPS3 services.

== internal API
The API used for communication between servers.

== feature flag
A string, sent as part of a FEATURES request, that identifies a set of
requests, responses, and/or states that constitute a feature provided by a
server.

== server
A program that provides services.

== service
A specific role in the BAPS3 system, usually defined as a group of expected
features.

== player service
The service responsible for playing single audio tracks.

== playlist service
The service responsible for maintaining track playlists for players.

== platform service
The service responsible for unifying other services into a coherent unit.

== URY
University Radio York.

== initial responses
The responses sent from servers to their clients upon connection.

== upstream
The services/servers implemented on top of the current subject.

== downstream
The services/servers on top of which the current subject is implemented.
