= Glossary

== Bifrost
The playout system specified in this document.

== API user
A user of a Bifrost API; either a client or a server.

== client
A program or user that consumes services.

== external API
The API used for communication between Bifrost clients and the server stack
providing Bifrost services.

== internal API
The API used for communication between servers.

== server
A program that provides services.

== role
A specific service in the Bifrost system.

== simple compound resource
A resource that relays requests to each of its child resources, and
aggregates the results.

== player service
The service responsible for playing single audio tracks.

== playlist service
The service responsible for maintaining track playlists for players.

== platform service
The service responsible for unifying other services into a coherent unit.

== tokenisation
The process of converting a _raw_ Bifrost protocol message into a
sequence of words, by separating on unquoted whitespace, removing
quote delimiters, and expanding escape sequences.

== URY
University Radio York.

== initial responses
The responses sent from servers to their clients upon connection.

== upstream
The services/servers implemented on top of the current subject.

== downstream
The services/servers on top of which the current subject is implemented.
