= Services

:Player:         link:player.adoc
:Playlist:       link:playlist.adoc
:TrackLister:    link:tracklister.adoc
:TrackResolver:  link:trackresolver.adoc
:Platform:       link:platform.adoc
:Client:         link:client.adoc
:Rationale:      link:rationale.adoc

BAPS3 is comprised of multiple logical _services_.  Each service
is intended to be implemented as a separate server program, but
__may__ be merged (for reasons of performance, maintainability, and
so on).

== Core Services

There are six _core services_ that define BAPS3's minimal functionality:

* {Player}[Player];
* {Playlist}[Playlist];
* {TrackLister}[Track Lister];
* {TrackResolver}[Track Resolver];
* {Platform}[Platform];
* {Client}[Client].

== Additional Services

Implementations of BAPS3 __may__ define additional services.  Examples
of possible services _not_ specified here include:

* Additional frontends (for debugging purposes, for example);
* Digitising and cataloguing services;
* Installation, deployment and configuration services.

== Core Functionality

All BAPS3 servers (consequently, all services) provide a minimum
amount of functionality associated with the BAPS3 protocol.  This
includes the following request:

* `quit` — Quits the service (including any downstream services).

In addition, the following responses _must_ be emitted by all
services at start-up, in this order:

* `OHAI` — Identifies the player implementation and welcomes the client;
* `FEATURES` — The set of features implemented by the service;
* `STATE` — The current service state (also emitted on state change).

All services will respond to a client request with one of the
following responses:

* `OK` — A client request was successfully honoured;
* `WHAT` — A client request was not understood;
* `FAIL` — An error has occurred.

== Chapter Structure

We begin this chapter by discussing the {rationale}[rationale] for
dividing the BAPS3 system into a comparatively large number of small
services.

Next, each core service is detailed in turn.  The services are
defined in terms of:

* Their remits;
* Their interfaces with other services (in brief; a more detailed specification
  follows in the next chapter);
* Their implementation requirements;
* Comparisons with existing software.


