= Compiling
:Antora:      https://antora.org
:Repository:  https://github.com/UniversityRadioYork/baps3-spec
:Issues:      https://github.com/UniversityRadioYork/baps3-spec/issues
:Fork:        https://github.com/UniversityRadioYork/baps3-spec/fork

This document may be compiled using {Antora}[Antora]; see that
project's documentation for details.

== Source

The latest source is available via its {Repository}[GitHub
repository].

== Makefile

The source distribution contains a GNU `Makefile`, which provides
a thin layer over common compilation tasks:

* `make` or `make book` will run `gitbook build`;
* `make serve` will run `gitbook serve`;
* `make gh-pages` will build the book, then checkout the `gh-pages`
  branch and commit the book's contents into that branch, and is
  useful for updating the Github Pages version of the specification.

NOTE: On operating systems such as FreeBSD, where the default `make`
is not GNU make, substitute the appropriate command for running GNU
make (usually `gmake`) for `make`.

== Contributing

To contribute to this specification:

. {Fork}[Fork] the specification on GitHub;
. Make any desired changes;
. Submit the changes as a _pull request_ via GitHub.

You can also submit issues via the GitHub {Issues}[issue page].
