= Feature: Playlist.AutoAdvance

Provides auto-advance functionality on a playlist.

Auto-advance, when enabled, intercepts an `END` response and
automatically `select`s the next `select`able item in the playlist,
if available.  Auto-advance thus skips over text items and other
non-playable playlist content.

== Dependencies

`Playlist.AutoAdvance` depends on both `End` and `Playlist`.

== Conflicts

`Playlist.AutoAdvance` may conflict with any other feature providing
auto-advance functionality.

== Requests

=== `autoadvance` — set auto-advance mode

==== Synopsis

`autoadvance [on|off]`

==== Description

`autoadvance` sets the current auto-advance mode.

An argument of `on` enables auto-advance; an argument of `off`
disables it.  If auto-advance is `on`, the server *should* handle
`END` responses as described above; if auto-advance is `off`, the
server *should not* do so.

== Responses

=== `AUTOADVANCE` — current auto-advance mode

==== Synopsis

`AUTOADVANCE [on|off]`

==== Description

`AUTOADVANCE` *should* be sent when:

* An upstream connects to this service, as part of the _initial
  responses_; *or*
* The auto-advance behaviour has changed.

The argument corresponds to the current auto-advance mode.
