= `list`

The `list` role maintains a playlist.

The playlist contains both _file items_, which represent
files available to load into the player, and _text items_, which
are comments that can be added into the playlist, but are not
loadable and will be skipped over by the playlist.

Servers implementing `list` have the following requirements:

Interface compatibility::
  Servers *must* provide the command interface described below.
  Servers *may* add further commands so long as they obey the specification.
File and text loads::
  Servers *must* allow both files and text items to be
  enqueued, and *must* disregard text items for the purposes of
  selection and auto-advancing.
Player mounting::
  Servers *must* expose a `player/file` at the mount point `player`.
  This player **may** be integrated into the `list`, so long as it obeys
  the mounting protocol.  The player **must** be fully controllable through
  the mounting protocol.
Flexible player selection::
  Servers *should* allow the configurable selection of the
  player instance to which it will attach, via the mounting protocol.
  If the playlist spawns, or contains, its own player,
  this may be disregarded.


== Dump format

The dump format for `list` is as follows.

* `AUTO` _autoload-type_.
* `COUNTL` _number-of-items_.
* Item dump (see below) **for each** index from `0` to _number-of-items - 1_.
* `ON` _player_ _request..._ **for each** dump item from the player.

=== Item dump format

*If* item _index_ is a file:

* `FLOADL` _index_ _hash_ _absolute-path_;

**Else if** item _index_ is text:

* `TLOADL` _index_ _hash_ _contents_.

== Commands

The `list` role adds the following commands:

=== Responses

`TLOADL` _index_ _hash_ _contents_::
  The playlist has enqueued a text item at index _index_ with the hash
  _hash_ and text _contents_.  If _index_ is below the client's last
  received `COUNTL`, the item previously at _index_ has been removed.
  If _index_ is equal to the client's last received `COUNTL`, the
  client **should** presume `COUNTL` has increased by one.  The server
  **may** re-send `COUNTL` to confirm this.  If _index_ is greater
  than the client's last received `COUNTL`, the client **should**
  request a `dump` to fill in the missing files.
`FLOADL` _index_ _hash_ _absolute-path_::
  The playlist has enqueued a file item at index _index_ with the hash _hash_
  and absolute path _absolute-path_.  The comments on indices above apply.
