= Rationale
:URY: http://ury.org.uk

_Bifrost_ is an architecture for a radio playout suite, designed to replace the
playout suite, _BAPS2_, in use at {URY}[University Radio York] as of 2016.

The primary goals for Bifrost are:

. To replace BAPS2 in use at University Radio York;
. To be easily modifiable, replaceable, and extensible;
. To take advantage of modern software, hardware and development technology;
. To be cross-platform (specifically focusing on Windows, Linux and FreeBSD);
. To be as reliable as, or more reliable than, BAPS2.

In addition, we hope that Bifrost will:

. Be useful to other independent radio stations;
. Be adaptable in the changing world of student radio;
. Allow a greater amount of flexibility within University Radio York than is
  currently available with BAPS2.

== The BAPS2 API

We have chosen to replace the existing BAPS2 API for the following reasons:

* The BAPS2 API is based on a binary protocol that is difficult to
  debug, and provides a lack of transparency that outweighs the
  performance advantages of using the binary protocol;
* The HTTP-based external API allows Web-based implementations of
  the client service, amongst other flexibility benefits;
* The change from BAPS2 to Bifrost allowed us to correct some oddities
  and counter-intuitive design decisions in the BAPS2 API.
