= Inter-Service Communications
:JSON:  http://json.org/

Unless implemented in the same server, BAPS3 services must talk to
each other to fulfil the tasks of a playout suite.  In this chapter
we discuss the standard protocol for BAPS3 services, _Bifrost_.
Bifrost is a resource-based protocol similar to a generalised HTTP.
We specify Bifrost as a generic protocol with two implementations:

* _Text Bifrost_, which is a lightweight, line-orientated textual
  API used  for communication between server-side services;
* _REST Bifrost_, which is a HTTP-based {JSON}[JSON] API used for
  communication specifically between the platform and client services.

These were previously known as the _internal_ and _External_ API
respectively.

== The BAPS2 API

We consciously chose not to use the existing BAPS2 API, for the
following reasons:

* The BAPS2 API is based on a binary protocol that is difficult to
  debug, and provides a lack of transparency that outweighs the
  performance advantages of using the binary protocol;
* The HTTP-based external API allows Web-based implementations of
  the client service, amongst other flexibility benefits;
* The change from BAPS2 to BAPS3 allowed us to correct some oddities
  and counter-intuitive design decisions in the BAPS2 API.

== Chapter Structure

We begin by discussing the basic structure common to both
implementations.  We then define both in turn, starting with the
internal API and following with the external API.  For each API,
the protocols underlying the API are first described, followed by
a detailed reference of the requests and responses used in that
API.
