= Bifrost Message Protocol

Bifrost servers and clients must talk to each other to fulfil the
tasks of a playout suite.  The Bifrost _message protocol_ is the base
protocol Bifrost servers and clients use to communicate.  It is
designed to meet the following criteria:

Composability::
  The API is intended to allow separate implementations of single
  services to be composed into a single logical service, by connecting
  servers together through the API.  Responses and requests not
  intended for a server with upstream and downstream connections
  respectively can be _forwarded_ transparently along the API
  connections;
Transparency::
  The API is text-based, and can be inspected by humans using either
  TCP/IP packet sniffing or connecting directly to services to be
  inspected;
Simplicity::
  The API uses a minimalistic line-orientated protocol, in which
  each line is comprised of one or more words, and uses shell-style
  word-escaping conventions (as well as C-style backslash escapes).
  It is relatively simple to implement, requires little to no
  external dependencies, and is modest in its usage of network
  bandwidth.

== The BAPS2 API

We consciously chose not to use the existing BAPS2 API, for the
following reasons:

* The BAPS2 API is based on a binary protocol that is difficult to
  debug, and provides a lack of transparency that outweighs the
  performance advantages of using the binary protocol;
* The HTTP-based external API allows Web-based implementations of
  the client service, amongst other flexibility benefits;
* The change from BAPS2 to BAPS3 allowed us to correct some oddities
  and counter-intuitive design decisions in the BAPS2 API.
